{{- if .Values.skeletoncache.api.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: skeletoncache
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: skeletoncache
  minReplicas: {{ max 1 (.Values.skeletoncache.api.hpa.minReplicas | default 1 | int) }}
  maxReplicas: {{ .Values.skeletoncache.api.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.skeletoncache.api.hpa.cpuTarget }}
{{- end }}
