apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ required "A valid .Values.environment is required!" .Values.environment }}-cert
spec:
  secretName: {{ required "A valid .Values.environment is required!"  .Values.environment }}-cert
  renewBefore: 720h
  dnsNames:
{{- range .Values.dnsHostnames }}
    - {{ . }}
{{- end }}
  issuerRef:
    name: {{required "A valid .Values.issuerName is required!"  .Values.issuerName }}
