apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.environment }}-cert
spec:
  secretName: {{ .Values.environment }}-cert
  renewBefore: 720h
  dnsNames:
{{- range .Values.dnsHostnames }}
    - {{ . }}
{{- end }}
  issuerRef:
    name: {{ .Values.issuerName }}
