{{ $gs := .Values.dns.googleSecret | required ".Values.dns.googleSecret is required." }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cloudDnsServiceAccountSecret | required ".Values.cloudDnsServiceAccountSecret is required." }}
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-issuer
    app.kubernetes.io/part-of: certmanager
  annotations: {}
type: Opaque
stringData:
  {{ $v := $gs }}
  {{ .Values.googleSecretFilename | default "google-secret.json" }}: {{ if kindIs "map" $v }}{{ $v | toJson | quote }}{{ else }}{{ $v | quote }}{{ end }}