{{- $raw := .Values.pychunkedgraph.tag | default .Values.pychunkedgraph.version | default .Chart.AppVersion -}}
{{- $tag := ternary $raw (printf "v%s" $raw) (hasPrefix "v" $raw) -}}
{{- $cluster_prefix := .Values.cluster.cluster_prefix | required ".Values.cluster.cluster_prefix is required." -}}
{{- $remeshSub := .Values.pychunkedgraph.remeshQueue | default (printf "%s_PCG_LOW_PRIORITY_REMESH" $cluster_prefix) -}}

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: remeshworker
spec:
  selector:
    matchLabels:
      app: remeshworker
  template:
    metadata:
      labels:
        app: remeshworker
    spec:
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "{{ .Values.cluster.meshPool }}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ .Values.cluster.meshPool }}
      volumes:
        - name: google-cloud-key
          secret:
            secretName: pychunkedgraph-google-cloud-key
      terminationGracePeriodSeconds: 20
      containers:
        - name: remeshworker
          image: {{ .Values.cluster.dockerRegistry }}/pychunkedgraph:{{ $tag }}
          imagePullPolicy: Always
          volumeMounts:
            - name: google-cloud-key
              mountPath: /root/.cloudvolume/secrets
          env: 
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/root/.cloudvolume/secrets/google-secret.json"
            {{- /* Inherit base PCG envs */}}
            {{- include "pcg_env.config" . | nindent 12 }}
            {{- /* Override queue to low-priority remesh, allow override via values */}}
            - name: PYCHUNKEDGRAPH_REMESH_QUEUE
              value: "{{ $remeshSub }}"
          resources:
            requests:
              memory: 3000Mi
              cpu: 800m
          command:
            - /bin/sh
            - -c
            - python -m workers.mesh_worker
