apiVersion: v1
kind: Secret
metadata:
  name: pychunkedgraph-google-cloud-key
type: Opaque
{{ $list := .Values.pychunkedgraph.secretFiles | default (list) }}
{{ if not (empty $list) }}
stringData:
  {{ $files := .Files }}
  {{ range $list }}
    {{ $v := .value }}
    {{ .name }}: {{ if kindIs "map" $v }}{{ $v | toJson | quote }}{{ else }}{{ $v | quote }}{{ end }}
  {{ end }}
{{ else }}
stringData: {}
{{ end }}
