logLevel: "warning"
pool: 
cluster:
  # required to fill in or choose
  globalServer: ""
  environment: ""
  domainName: ""
  googleProject: ""
  googleRegion: "us-east1"
  googleZone: "us-east1-b"
  # likely fine as defaults
  lightweightPool: "lightweight-pool"
  meshPool: "mesh-pool"
  standardPool: "standard-pool"
  dockerRegistry: "docker.io/caveconnectome"

tourguide:
  # image tag; defaults to Chart.appVersion if empty
  tag: ""