apiVersion: v1
kind: ConfigMap
metadata:
  name: pcgl2cache-config
  labels:
    app: pcgl2cache
  annotations:
    checksum/config: {{ toJson .Values.pcgl2cache.config | sha256sum }}
data:
  config.cfg: |
    # Provided via values or external tool
    {{- /* Intentionally left for external injection */ -}}
{{ .Values.pcgl2cache.config.configCfg | indent 4 }}
  L2_table_map.yml: |
    # Provided via values or external tool
{{ .Values.pcgl2cache.config.l2TableMap | indent 4 | required "pcgl2cache.config.l2TableMap is a required value, if you do not have a level 2 cache, do not deploy the level 2 cache service" }}
