apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pcgl2cache-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pcgl2cache
  minReplicas: {{ .Values.pcgl2cache.api.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.pcgl2cache.api.hpa.maxReplicas | default 5 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.pcgl2cache.api.hpa.cpuTarget | default 80 }}

