{{- $domain := .Values.cluster.domainName | required ".Values.cluster.domainName is required." -}}
{{- $prefix := .Values.cluster.cluster_prefix | required ".Values.cluster.cluster_prefix is required." -}}
{{- $defaultHost := printf "%s.%s" $prefix $domain -}}
{{- $dnsEntries := .Values.cluster.dns_entries | default (list) -}}
{{- $raw := append (default (list) $dnsEntries) $defaultHost -}}
{{- $hosts := uniq $raw -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  {{- range $hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 80
      - path: /sticky_auth
        pathType: Prefix
        backend:
          service:
            name: sticky-auth-service
            port:
              number: 80
  {{- end }}

