cluster:
  dockerRegistry: docker.io/caveconnectome
  globalServer: ""
  dns_entries: []
  meshPool: mesh-pool
  cluster_prefix: ""

skeletoncache:
  tag: "0.22.36"
  # Per-endpoint rate limits (requests per minute).
  # Units: per-minute. The chart renders these as "<N>/minute" for LIMITER_CATEGORIES.
  limits:
    get_refusal_list: 100
    query_cache: 100
    skeleton_exists: 100
    get_skeleton_that_exists: 1000
    get_skeleton_that_doesnt_exist: 10
    get_skeleton_via_msg_that_exists: 1000
    get_skeleton_via_msg_that_doesnt_exist: 10
    get_skeletons_bulk: 10
    get_skeletons_bulk_async: 10
  api:
    enabled: true
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      cpuTarget: 80
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
  worker:
    minReplicas: 0
    maxReplicas: 50
    resources:
      requests:
        memory: 1000Mi
        cpu: 200m
  limiter:
    uri: ""
    categories: ""
  datastackRemap: "{}"
  cacheNonH5: "false"
  verboseLevel: "0"
  # Default debug root id; set to a non-zero root ID to enable targeted debugging
  debugRootId: "0"
  queues:
    high: ""
    low: ""
  # Required: Pub/Sub subscription names (no defaults provided)
  high: ""
  low: ""
  deadLetter: ""
  exchanges:
    high: ""
    low: ""
  bigtable:
    instance: ""
  # Optional: full gs:// cloud path (bucket and optional prefix)
  cloudPath: ""
  # Optional secret files rendered into a Kubernetes Secret for mounting
  # Each entry is a name and value; value can be a string or a ref+gcpsecrets:// URI
  secretFiles:
    - name: google-secret.json
      value: ""
    - name: cave-secret.json
      value: ""
  statsExporter:
    enabled: false
    pollSeconds: 30

keda:
  enabled: true
  pollingSeconds: 15
  cooldownSeconds: 600
  activationValue: 0
  timeHorizon: "2m"
  valueIfNull: 0
  pubsub:
    messagesPerWorker: 1

gmp:
  enabled: false
  scrape:
    interval: 30s
