cluster:
  dockerRegistry: docker.io/caveconnectome
  globalServer: ""
  dns_entries: []
  meshPool: mesh-pool
  cluster_prefix: ""

image:
  tag: latest

skeletoncache:
  api:
    enabled: true
    hpa:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      cpuTarget: 80
    resources:
      requests:
        memory: 512Mi
        cpu: 200m
  worker:
    minReplicas: 0
    maxReplicas: 50
    resources:
      requests:
        memory: 1000Mi
        cpu: 200m
  limiter:
    uri: ""
    categories: ""
  datastackRemap: "{}"
  cacheNonH5: "false"
  verboseLevel: "0"
  debugRootId: ""
  queues:
    high: ""
    low: ""
  # Required: Pub/Sub subscription names (no defaults provided)
  high: ""
  low: ""
  deadLetter: ""
  exchanges:
    high: ""
    low: ""
  bigtable:
    instance: ""
  # Optional: full gs:// cloud path (bucket and optional prefix)
  cloudPath: ""
  statsExporter:
    enabled: false
    pollSeconds: 30

keda:
  enabled: true
  pollingSeconds: 15
  cooldownSeconds: 600
  activationValue: 0
  timeHorizon: "2m"
  valueIfNull: 0
  pubsub:
    messagesPerWorker: 1

gmp:
  enabled: false
  scrape:
    interval: 30s
