limiter:
  redis:
    host: ""
cluster:
  # required to fill in or choose
  globalServer: ""
  environment: ""
  domainName: ""
  googleProject: ""
  dataProjectName: ""
  googleRegion: "us-east1"
  googleZone: "us-east1-b"
  # likely fine as defaults
  standardPool: "standard-pool"
  dockerRegistry: "docker.io/caveconnectome"
  # optional, used to build Pub/Sub subscription names
  cluster_prefix: ""
pychunkedgraph:
  # image tag; defaults to Chart.appVersion if empty; legacy .version still honored in templates
  tag: ""
  # should be a list of graphIds seperated by commas
  graphIds: ""
  secretFiles:
    # need to fill in with path to service account secret file
    - name: google-secret.json
      value: ""
    # need to fill in with path to secret file
    - name: cave-secret.json
      value: ""
    # should add any other secret files you need here
  config: ""
  redis:
    host: ""
    port: 6379
  bigtableInstanceName: "pychunkedgraph"
  writeMinReplicas: 1
  writeMaxReplicas: 3
  writeMemGb: 4
  writeCpuMilli: 500
  readMinReplicas: 1
  readMaxReplicas: 10
  readMemGb: 1.8
  readCpuMilli: 125
  meshMinReplicas: 1
  meshMaxReplicas: 3
  meshMemGb: 4
  meshCpuMilli: 1000
  meshWorkerMinReplicas: 0
  meshWorkerMaxReplicas: 10
  remeshQueue: 
  # should be enable or left blank
  enableLogs: "enable"
  # should be the name of table you want to log leave_many for
  logsLeavesMany: ""
  limitsFastQueryPerMinute: 1000
  limitsQueryPerMinute: 100

# KEDA-based scaling controls
keda:
  enabled: true
  # enable KEDA scaling for meshworker; when true, HPA is disabled and KEDA ScaledObject is created
  meshWorker:
    # How many messages per worker we target; 1 means aim for ~1 message per active worker
    messagesPerWorker: 1
    # Polling and cooldown periods (seconds)
    pollingSeconds: 30
    cooldownSeconds: 60