apiVersion: v1
kind: ConfigMap
metadata:
  name: cavecanary-config
data:
  config.cfg: |
    [SETTINGS]
    DATASTACK_NAME = {{ .Values.cavecanary.datastacks | toJson}}
    SERVER_ADDRESS = https://{{ .Values.cluster.globalServer }}
    SLACK_API_TOKEN = {{ .Values.slack.api_token }}
    SLACK_CHANNEL = {{ .Values.slack.canary_channel }}
    NUM_TEST_ANNOTATIONS = 1000
    CHECK_INTERVAL = 60
    DATABASE_URI = postgresql+asyncpg://{{ .Values.cloudsql.username}}:{{ .Values.cloudsql.password}}@127.0.0.1:3306/annotation
