apiVersion: v2
name: cert-manager-google
version: 0.1.0
description: "Installs Cert-Manager an Issuer and a Certificate on google cloud"

# The key part: we declare the dependency on the official cert-manager chart:
dependencies:
  - name: cert-manager
    version: 1.8.0                   
    repository: "https://charts.jetstack.io"
    condition: certManager.enabled         # so we can toggle it on/off
    tags:
      - certManager
      