cluster: {}
emannotationschemas:
  # Max request body ingress-nginx will accept for this service (nginx default is 1m).
  ingress:
    proxyBodySize: "10m"
  # tag: ""
  replicas: 1
  serviceAccountSecret: ""
  googleSecretFilename: google-secret.json
  resources:
    requests:
      memory: 130Mi
      cpu: 50m
  env: {}
