{{- $global_server := .Values.cluster.globalServer | required ".Values.cluster.globalServer is required." }}
{{- $raw := .Values.materialize.tag | default .Values.materialize.version | default .Chart.AppVersion   -}}
{{- $tag := ternary $raw (printf "v%s" $raw) (hasPrefix "v" $raw) -}}
{{- $apipool := .Values.materialize.apipool | default .Values.cluster.lightweightPool | required "materialize.apipool or cluster.lightweightPool is required" -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: materialize
spec:
  selector:
    matchLabels:
      app: materialize
  template:
    metadata:
      labels:
        app: materialize
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/materialize_secret.yaml") . | sha256sum }}
        checksum/cloudsql: {{ include (print $.Template.BasePath "/cloudsql_secret.yaml") . | sha256sum }}
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.ip_local_port_range
            value: "1024 65535"
      tolerations:
        - key: "pool"
          operator: "Equal"
          value: "{{ $apipool }}"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: {{ $apipool }}
      volumes:
        - name: materializationengine-config-volume
          configMap:
            name: materializationengine-config
        # Other volumes...
        - name: google-cloud-key
          secret:
            secretName: materialize-google-cloud-key
        - name: cloudsql-instance-credentials-volume
          secret:
            secretName: mat-cloudsql-google-cloud-key
      containers:
        - name: materialize
          image: {{ .Values.cluster.dockerRegistry }}/materializationengine:{{ $tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 9192
          volumeMounts:
            - name: google-cloud-key
              mountPath: /home/nginx/.cloudvolume/secrets
            - name: materializationengine-config-volume
              mountPath: /app/materializationengine/instance/
          env:
            - name: MATERIALIZATION_ENGINE_SETTINGS
              value: /app/materializationengine/instance/config.cfg
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/google-secret.json
            - name: AUTH_URI
              value: {{ .Values.cluster.globalServer }}/auth
            - name: QUEUE_LENGTH_LIMIT
              value: "5001"
            - name: QUEUES_TO_THROTTLE
              value: process
            - name: THROTTLE_QUEUES
              value: "true"
            - name: LIMITER_CATEGORIES
              value: '{"query":"{{ .Values.materialize.limitsQueryPerMinute}}/minute","fast_query":"{{ .Values.materialize.limitsFastQueryPerMinute}}/minute"}'
            - name: LIMITER_URI
              value: redis://{{ .Values.limiter.redis.host }}/0 
            - name: STICKY_AUTH_URL
              value: {{ .Values.cluster.globalServer }}/sticky_auth
            - name: AUTH_URL
              value: {{ .Values.cluster.globalServer }}/auth
            - name: INFO_URL
              value: {{ .Values.cluster.globalServer }}/info
            - name: DAF_CREDENTIALS
              value: /home/nginx/.cloudvolume/secrets/cave-secret.json
          resources:
            requests:
              memory: {{ .Values.materialize.resources.requests.memory | default "800Mi" }}
              cpu: {{ .Values.materialize.resources.requests.cpu | default "200m" }}
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 60
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 60
        - name: uwsgi-exporter
          image: caveconnectome/uwsgi-export-workers:v14
          # Exposes the metrics endpoint on 0.0.0.0:9101
          ports:
              - containerPort: 9101
          env:
          # This tells the exporter where to find the uWSGI stats server
          - name: UWSGI_STATS_URL
            value: "http://localhost:9192"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 50m
              memory: 64Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
      initContainers:
        - name: sysctl-buddy
          image: alpine:3.4
          command:
            - /bin/sh
            - -c
            - sysctl -w net.core.somaxconn=32768
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          resources:
            requests:
              memory: 10Mi
              cpu: 5m
        - name: cloudsql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.23.0
          restartPolicy: Always
          args:
            - "--port=3306"
            - "--credentials-file=/secrets/cloudsql/google-secret.json"
            - "--max-sigterm-delay=3600s"
            - "{{ .Values.cluster.googleProject}}:{{ .Values.cluster.googleRegion}}:{{ .Values.cloudsql.sqlInstanceName }}"
          env:
            - name: CSQL_PROXY_HEALTH_CHECK
              value: "true"
            - name: CSQL_PROXY_HTTP_PORT
              value: "9801"
            - name: CSQL_PROXY_HTTP_ADDRESS
              value: 0.0.0.0
            - name: CSQL_PROXY_QUITQUITQUIT
              value: "true"
            - name: CSQL_PROXY_ADMIN_PORT
              value: "9092"
            - name: CSQL_PROXY_STRUCTURED_LOGS
              value: "true"
          ports:
            - containerPort: 9801
              protocol: TCP
          resources:
            requests:
              memory: 8Mi
              cpu: 10m
          securityContext:
            runAsUser: 2 # non-root user
            allowPrivilegeEscalation: false
          startupProbe:
            failureThreshold: 60
            httpGet:
              path: /startup
              port: 9801
              scheme: HTTP
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 10
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /liveness
              port: 9801
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 9801
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "curl -f -X POST http://localhost:9092/quitquitquit || kill -15 1"]
          volumeMounts:
            - name: cloudsql-instance-credentials-volume
              mountPath: /secrets/cloudsql
              readOnly: true
