{{- if not .Values.keda.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: materialize-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: materialize
  minReplicas: {{ max 1 (.Values.materialize.apiMinReplicas | default 1 | int) }}
  maxReplicas: {{ .Values.materialize.apiMaxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
{{- if .Values.gmp.enabled }}
    - type: Pods
      pods:
        metric:
          name: prometheus.googleapis.com|uwsgi_perc_busy_workers|gauge
        target:
          type: AverageValue
          averageValue: 75
{{- end }}
{{- end }}