{{- $domain := .Values.cluster.domainName | required ".Values.cluster.domainName is required." -}}
{{- $prefix := .Values.cluster.cluster_prefix | required ".Values.cluster.cluster_prefix is required." -}}
{{- $defaultHost := printf "%s.%s" $prefix $domain -}}
{{- $dnsEntries := .Values.cluster.dns_entries | default (list) -}}
{{- $raw := append (default (list) $dnsEntries) $defaultHost -}}
{{- $hosts := uniq $raw -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: materializationengine-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "360"
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
spec:
  ingressClassName: nginx
  rules:
  {{- range $hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /materialize
        pathType: ImplementationSpecific
        backend:
          service:
            name: materialize-service
            port:
              number: 80
  {{- end }}
