{{- if .Values.keda.enabled }}
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: materialize-api
  annotations:
    validations.keda.sh/hpa-ownership: "true"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: materialize
  minReplicaCount: {{ .Values.materialize.apiMinReplicas }}
  maxReplicaCount: {{ .Values.materialize.apiMaxReplicas }}
  triggers:
    {{- if .Values.gmp.enabled }}
    # busy-workers % scraped via GMP; only present when gmp is enabled.
    - type: prometheus
      authenticationRef:
        name: keda-gcm-auth
      metadata:
        serverAddress: https://monitoring.googleapis.com/v1/projects/{{ .Values.cluster.googleProject }}/location/global/prometheus
        query: >-
          avg(avg_over_time(uwsgi_perc_busy_workers{cluster="{{ .Values.cluster.cluster }}",namespace="{{ .Release.Namespace }}",top_level_controller_name="materialize"}[1m])) or vector(0)
        # Target AverageValue in percent
        threshold: "75"
    {{- end }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: "75"
{{- end }}
