{{- $cloudsql_pw := .Values.cloudsql.password | required ".Values.cloudsql.password is required." }}
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.cloudsql.username }}:{{ .Values.cloudsql.password }}@127.0.0.1:{{ .Values.cloudsql.port | default "5432" }}/{{ .Values.cloudsql.database | default "cave_catalog" }}"
