apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalog-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalog
  minReplicas: {{ .Values.catalog.minReplicas | default 1 }}
  maxReplicas: {{ .Values.catalog.maxReplicas | default 3 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
