apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pmanagement-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pmanagement
  minReplicas: {{ .Values.pmanagement.minReplicas }}
  maxReplicas: {{ .Values.pmanagement.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90