{{- $domain := .Values.cluster.domainName | required ".Values.cluster.domainName is required." -}}
{{- $prefix := .Values.cluster.cluster_prefix | required ".Values.cluster.cluster_prefix is required." -}}
{{- $host := printf "%s.%s" $prefix $domain -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tourguide-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /tourguide
        pathType: ImplementationSpecific
        backend:
          service:
            name: tourguide-service
            port:
              number: 80
